### ISSUE TITLE
Joint Shap for DeepExplainer

### ISSUE THREAD

**Issue by yagmurn** [harris-chris/joint-shapley-values#1]
Hi,

I am trying to adapt your "boston-housing-walkthrough" example to LSTM models with DeepExplainer.
I got an error below:
coalitions_to_k = get_powerset_to_k(n_features, 2)
explainer = shap.DeepExplainer(model, x_train)

baseline = explainer(x_test)

def value_function(cln_X):
    return model.predict(cln_X)# - baseline[0]

TypeError                                 Traceback (most recent call last)
<ipython-input-41-8ea35a9fe05f> in <module>
      2 explainer = shap.DeepExplainer(model, x_train)
      3 
----> 4 baseline = explainer(x_test)
      5 
      6 def value_function(cln_X):

TypeError: 'DeepExplainer' object is not callable

Could you please help me? I could not find any example about joint shap with deep learning.

**Comment by harris-chris** [comment]
Hello - are you able to share your code? It sounds like there might be a
simple error somewhere.

**Comment by yagmurn** [comment]
Hello again,
[data_shap.zip](https://github.com/harris-chris/joint-shapley-values/files/12079814/data_shap.zip)

The code and data are in the attached files. 
I did not use the base values to move on the other part. But now I faced with the dimension error. Could you please help me?

Thank you so much.

**Comment by harris-chris** [comment]
Hello, sorry, if it's a simple thing I might be able to help but I don't
have time to debug longer code.

**Comment by yagmurn** [comment]
Okey, thank you again.
